#spring.application.name=quiz-service

server:
  port: 1211

# db configuration aws
#spring.datasource.url=jdbc:mysql://apostle-new.c714jf680afz.ap-south-1.rds.amazonaws.com:3306/schoolERP

# db connection offline
#spring.datasource.url=jdbc:mysql://localhost:3306/apostle_api
#
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# create, delete, validate -> other options
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true



#security:
#  jwt:
#    secret-key: "jwt-tokens-that-should-be-changed-production"

spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update

    show-sql: true
